export { default as Navbar } from './base-navbar.vue'
export { default as Sidebar } from './sidebar/base-sidebar.vue'
export { default as Settings } from './settings/base-settings.vue'
export { default as AppMain } from './app-main.vue'
export { default as TagsView } from './tagsView/base-tags-view.vue'
